networks:
  hls-variants-network:
    driver: bridge

services:
  rabbit:
    image: 'rabbitmq:3.7.4'
    container_name: hls-variants-broker
    hostname: hls-variants-broker
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "example"
    volumes:
      - './rabbitmq/rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins'
    networks:
      - hls-variants-network
  mongo:
    image: mongo:4.2
    container_name: hls-variants-mongo
    hostname: hls-variants-mongo
    networks:
      - hls-variants-network
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=hls-variants-info
      - MONGO_INITDB_USER=admin
      - MONGO_INITDB_PWD=admin
  app:
    container_name: hls-variants-info
    environment:
      - MONGO_HOSTNAME=hls-variants-mongo
      - RABBIT_HOSTNAME=hls-variants-broker
      - RUNS_IN_CONTAINER=true
    build: .
    deploy:
      resources:
        limits:
          cpus: '1'
    ports:
      - '3000:3000'
    depends_on:
      - rabbit
      - mongo
    networks:
      - hls-variants-network
