name: Push to feature
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x.x
          cache: npm
      
      - name: Install dependencies
        run: npm install && npm i -g mocha

      - name: Run tests
        run: npm run test